# Site settings
title: Exorust
description: A portfolio of Chandrahas' Work
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chandrahas Aroori
user_description: I am a student pursuing his undergraduate in Computer Science in Bits Pilani Hyderabad Campus.
user_title: Software Developer
email: chandrahas.aroori@gmail.com
twitter_username: lorem_ipsum
github_username:  Exorust
gplus_username:  lorem_ipsum
stackoverflow:      7086962/chandrahas-aroori
linkedin:           chandrahas-aroori-409b44148/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
